#! /usr/bin/env bash
# Ian Taylor 2017

# Load all necessary files containing exercises
# Use rlwrap to make the REPL actually useable ><

rlwrap scheme --load \
helpers.scm \
3_cons_the_magnificent.scm \
4_numbers_games.scm \
5_full_of_stars.scm \
6_shadows.scm \
7_friends_and_relations.scm \
8_lambda_the_ultimate.scm \
9_and_again_and_again.scm \
